# Generated by Django 2.2.3 on 2019-07-26 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('comment', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('is_custom', models.BooleanField(default=True)),
                ('is_gpio', models.BooleanField(default=True)),
                ('comment', models.CharField(blank=True, max_length=40)),
                ('format', models.TextField(blank=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='units.Family')),
            ],
            options={
                'db_table': 'units',
            },
        ),
    ]
