# Generated by Django 2.2.3 on 2019-07-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Семейство', 'verbose_name_plural': 'Семейства'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Компонент', 'verbose_name_plural': 'Компоненты'},
        ),
    ]
