# Generated by Django 2.2.2 on 2019-07-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0003_auto_20190701_1127'),
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='role',
            field=models.ForeignKey(default=None, on_delete=models.SET(2), to='Roles.Roles'),
        ),
    ]
