# Generated by Django 2.2.2 on 2019-07-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_profiles_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='user',
            new_name='auth',
        ),
    ]
