# Generated by Django 2.2.2 on 2019-07-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_auto_20190702_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='role',
            field=models.ForeignKey(default=2, on_delete=models.SET(2), to='auth.Group'),
        ),
    ]
