# Generated by Django 2.2.2 on 2019-07-01 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0002_auto_20190701_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Clients.Clients')),
            ],
        ),
    ]
