# Generated by Django 2.2.2 on 2019-07-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
