# Generated by Django 2.2.2 on 2019-07-01 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0002_auto_20190701_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Clients.Clients'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
