# Generated by Django 2.2.2 on 2019-07-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0003_auto_20190701_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='uid',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
