# Общие параметры:
device:
  id: FP-1
  location: Адрес банкомата
  broker:
    host: 89.223.27.69
    port: 1883
    keepalive: 60

# Датчики GPIO:
gpio:
  led1: &l1
    pin: 17

  led2: &l2
    pin: 27

  out1: &o1
    pin: 5

  out2: &o2
    pin: 13

  out3: &o3
    pin: 26

  out4: &o4
    pin: 16

  in1: &i1
    pin: 21

  in2: &i2
    pin: 18

  in3: &i3
    pin: 23

  in4: &i4
    pin: 24

  in5: &i5
    pin: 25

  cnt1: &c1
    pin: 6

  cnt2: &c2
    pin: 19

  cnt3: &c3
    pin: 12

  cnt4: &c4
    pin: 20

  volt: &v
    pin: 9

  block: &b
    pin: 11

# Аналоговые датчики:
analog:
  cpu: &t1
    min: 0.0
    max: 100.0
    threshold: 80.0
    hysteresis: 0.9
    timedelta: 60
  ext: &t2
    min: 10.0
    max: 80.0
    threshold: 70.0
    hysteresis: 0.7
    timedelta: 45

# Раскладка в группы по функциональности:
units:
  leds: &u1
    led1: *l1
    led2: *l2

  ins: &u2
    in1: *i1
    in2: *i2
    in3: *i3
    in4: *i4
    in5: *i5

  couts: &u3
    cmp1:
      out1: *o1
      cnt1: *c1
    cmp2:
      out2: *o2
      cnt2: *c2
    cmp3:
      out3: *o3
      cnt3: *c3
    cmp4:
      out4: *o4
      cnt4: *c4

  temp: &u4
    cpu: *t1
    ext: *t2

  misc: &u5
    volt: *v
    # block: *b
