device:
  address: "\u0433.  \u041F\u0430\u0432\u043B\u043E\u0434\u0430\u0440"
  name: FP-1
mqtt:
  broker:
    host: 89.223.27.69
    keepalive: 60
    port: 1883
snmp:
  community: public
  host: demo.snmplabs.com:161
  # host: 127.0.0.1:161
  password: psw
  user: user
  version: 2c
units:
  ins:
    in1:
      pin: 21
    in2:
      pin: 18
    in3:
      pin: 23
    in4:
      pin: 24
    in5:
      pin: 25
  leds:
    led1:
      pin: 17
    led2:
      pin: 27
  misc:
    lock:
      pin: 11
    volt:
      pin: 9
  temp:
    cpu: {}
    ext: {}
complects:
  couts:
    cnt1:
      pin: 6
      src: out1
    cnt2:
      pin: 19
      src: out2
    cnt3:
      pin: 12
      src: out3
    cnt4:
      pin: 20
      src: out4
    out1:
      pin: 5
    out2:
      pin: 13
    out3:
      pin: 26
    out4:
      pin: 16
