complects:
  couts:
    cmp1:
      cnt:
        pin: 9
      out:
        pin: 8
    cmp2:
      cnt:
        pin: 11
      out:
        pin: 10
    cmp3:
      cnt:
        pin: 13
      out:
        pin: 12
    cmp4:
      cnt:
        pin: 15
      out:
        pin: 14
device:
  broker:
    host: 89.223.27.69
    keepalive: 60
    port: 1883
  id: FP-2
  location: "\u0433.\u041F\u0430\u0432\u043B\u043E\u0434\u0430\u0440"
units:
  ins:
    in1:
      pin: 3
    in2:
      pin: 4
    in3:
      pin: 5
    in4:
      pin: 6
    in5:
      pin: 7
  leds:
    led1:
      pin: 1
    led2:
      pin: 2
  misc:
    block:
      pin: 17
    volt:
      pin: 16
  temp:
    cpu: {}
    ext: {}
