complects:
  couts:
    cmp1:
      cnt:
        pin: 6
      out:
        pin: 5
    cmp2:
      cnt:
        pin: 19
      out:
        pin: 13
    cmp3:
      cnt:
        pin: 12
      out:
        pin: 26
    cmp4:
      cnt:
        pin: 20
      out:
        pin: 16

device:
  id: FP-2
  location:
    "\u0433\u043E\u0440\u043E\u0434 \u041E\u043C\u0441\u043A \u0443\u043B\u0438\
    \u0446\u0430 \u041C\u0438\u0440\u0430 33\u0410 \u043A\u0430\u0431\u0438\u043D\u0435\
    \u0442 503"

units:
  ins:
    in1:
      pin: 21
    in2:
      pin: 18
    in3:
      pin: 23
    in4:
      pin: 24
    in5:
      pin: 25
  leds:
    led1:
      pin: 17
    led2:
      pin: 27
  misc:
    lock:
      pin: 11
    volt:
      pin: 9
  temp:
    cpu: {}
    ext: {}

mqtt:
  broker:
    host: 89.223.27.69
    port: 1883
    keepalive: 60
