# Generated by Django 2.2.2 on 2019-07-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0004_auto_20190704_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.TextField(max_length=255),
        ),
    ]
