# Generated by Django 2.2.2 on 2019-07-04 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0005_auto_20190704_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('type', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='settings',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Settings.Types'),
        ),
    ]
