# Generated by Django 2.2.2 on 2019-07-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0006_auto_20190704_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
