#!/bin/bash

if [ -z $1 ]; then
    echo "No parameters found"
    exit 0
fi

action=$1

function server_start {
    # uwsgi
    /usr/local/bin/uwsgi --emperor --ini /var/www/focus/nginx/focus_uwsgi.ini > /dev/null 2> /dev/null &

    # websocket
    /usr/local/bin/forever start /var/www/focus/node_server/server.js &
}

function server_stop {
    # killall uwsgi -s 9
    /usr/local/bin/forever stop /var/www/focus/node_server/server.js
}


if [ $action == "start" ]; then 
    server_start
elif [ $action == "stop" ]; then
    server_stop
elif [ $action == "restart" ]; then
    server_stop
    server_start
fi
