# Generated by Django 2.2.2 on 2019-07-02 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0003_auto_20190701_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='roles',
            name='group_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Roles.Group'),
        ),
    ]
