# Generated by Django 2.2.2 on 2019-07-02 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0004_auto_20190702_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='group_name',
            new_name='group',
        ),
    ]
