# Generated by Django 2.2.2 on 2019-07-02 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0005_auto_20190702_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Roles.Group'),
        ),
    ]
