# Generated by Django 2.2.3 on 2019-08-23 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='devices.Config'),
        ),
    ]
