# Generated by Django 2.2.2 on 2019-07-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceUnits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
