# Generated by Django 2.2.2 on 2019-07-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceUnits', '0004_meter_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='comment',
            new_name='title',
        ),
    ]
