# Generated by Django 2.2.2 on 2019-07-05 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0004_devices_uid'),
        ('DeviceUnits', '0005_auto_20190704_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(default='{}')),
                ('comment', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('device', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Devices.Devices')),
                ('unit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DeviceUnits.Units')),
            ],
        ),
        migrations.DeleteModel(
            name='Meter',
        ),
    ]
