# Generated by Django 2.2.2 on 2019-07-05 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceUnits', '0006_auto_20190705_0342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='comment',
            new_name='title',
        ),
    ]
