# Generated by Django 2.2.2 on 2019-07-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceUnits', '0007_auto_20190705_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientunits',
            name='state',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
