# Generated by Django 2.2.2 on 2019-07-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceUnits', '0008_auto_20190705_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientunits',
            name='is_custom',
            field=models.BooleanField(default=True),
        ),
    ]
