# Generated by Django 2.2.2 on 2019-07-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceUnits', '0009_clientunits_is_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientunits',
            name='is_custom',
        ),
        migrations.AddField(
            model_name='units',
            name='is_custom',
            field=models.BooleanField(default=True),
        ),
    ]
