# Generated by Django 2.2.2 on 2019-07-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceUnits', '0012_family_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
