# Generated by Django 2.2.2 on 2019-07-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceUnits', '0013_auto_20190712_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
