# Generated by Django 2.2.2 on 2019-07-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceUnits', '0015_gpioconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='format',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
