# Generated by Django 2.2.2 on 2019-07-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceUnits', '0016_units_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpioconfig',
            name='format',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='format',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
