# Generated by Django 2.2.2 on 2019-07-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceUnits', '0017_auto_20190715_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpioconfig',
            name='pin',
            field=models.SmallIntegerField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
