# Generated by Django 2.2.3 on 2019-07-26 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datatype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'config_datatypes',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'config_groups',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('comment', models.CharField(default=None, max_length=80)),
                ('value', models.CharField(max_length=16)),
                ('datatype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Datatype')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.Group')),
            ],
            options={
                'db_table': 'config',
            },
        ),
    ]
