# Generated by Django 2.2.3 on 2019-07-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='comment',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
