# Generated by Django 2.2.3 on 2019-07-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20190726_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name': 'Конфигурация', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterModelOptions(
            name='datatype',
            options={'verbose_name': 'Тип данных', 'verbose_name_plural': 'Типы данных'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
